### PR TITLE
Removed node_modules, Added single index.js file

### PR DESCRIPTION
**Pull request by mehdi-ra**
Closes #000

### Types of changes

  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [x] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to change)

Because the node_modules were such a pain for development.

- Removed node_modules
- Added ncc build to build one single index.js
- Modified the `action.yaml` due to changes.
- Now you need to run `npm run build` then `npm run package` then push built files in dist directory to repository.

Just try to use my forked repository as github action on a test env then specify the branch i made as version. If anything was wrong tell me and i will fix it.

### CODE REVIEW

**Comment by mehdi-ra** [comment]
Your welcome dear @YunaBraska and thank you for this amazing action.
I found this out back when I opened an issue and I had this in my mind until I found free time to apply this.
Yes, the index.js inside the dist folder is completely standalone and does not need any other node_modules to run you can check the lib folder files size and dist folder size. There is a huge difference.
I tested this and works fine without error but the functionality is important to check if there is any runtime error or not.
### Build commands
I will combine two commands into one single command and then I'll push it.

**Comment by mehdi-ra** [comment]
@YunaBraska Now you can use `npm run release` command to build and package.

**Comment by YunaBraska** [comment]
@mehdi-ra 
I just realized that my pipelines for tests are not running on forks and I also can't contribute on a fork to just set up a pipeline... I never worked with forks -_- _That's another topic to solve later_

I would like to merge this PR into (feat/ncc-build)[https://github.com/YunaBraska/git-info-action/tree/feat/ncc-build].
There I can take it over and test the change against multiple Operating Systems...
**Can you please resolve the conflicts**? Then I can merge and start.

**Comment by YunaBraska** [comment]
Yes, its on the latest commit. The code was updating itself today. 📦

**Comment by mehdi-ra** [comment]
@YunaBraska it's good to go.

**Comment by YunaBraska** [comment]
@mehdi-ra Well done! It seems to work like a charm. All three main OS worked with it 👍 Amazing.

**Comment by mehdi-ra** [comment]
You're welcome. Till next contributions ...
@YunaBraska

**Pull request merged**
